<?php
namespace App\SpotTraining\Postflop\Modules;

use App\SpotTraining\Postflop\Concerns\BuildsPostflopSpots;

class DonkBetSpots
{
    use BuildsPostflopSpots;

    public static function all(): array
    {
        return array_map(fn (array $spot): array => self::build($spot), self::spots());
    }

    protected static function build(array $s): array
    {
        return self::spot(
            $s['id'],
            'donk_bet',
            'Donk Bet Flop',
            $s['concept'],
            $s['concept_label'],
            $s['title'],
            $s['hero_position'],
            $s['villain_position'],
            $s['hero_cards'],
            $s['board_cards'],
            $s['pot_bb'],
            $s['spr'],
            $s['effective_stack_bb'],
            $s['board_texture'],
            $s['range_advantage'],
            $s['nut_advantage'],
            $s['actions'],
            $s['options'],
            $s['correct_action'],
            $s['explanation'],
            $s['solver_note'],
            $s['grades'],
            $s['gto_insight'],
            $s['low_stakes_insight'],
            $s['confidence']
        );
    }

    protected static function spots(): array
    {
        return [
            [
                'id' => "pf_donk_765ss_bb_vs_btn_98s",
                'concept' => "board_favors_bb",
                'concept_label' => "Donk en board que favorece BB",
                'title' => "BB vs BTN · 98s en 765ss",
                'hero_position' => "BB",
                'villain_position' => "BTN",
                'hero_cards' => ["9s", "8s"],
                'board_cards' => ["7s", "6d", "5s"],
                'pot_bb' => 5.5,
                'spr' => 8.1,
                'effective_stack_bb' => 47.0,
                'board_texture' => "Board bajo muy conectado",
                'range_advantage' => "BTN tiene overpairs, pero BB impacta más la textura.",
                'nut_advantage' => "BB tiene más escaleras, dobles y combo draws.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: 7♠ 6♦ 5♠", "Action on Hero BB"],
                'options' => ["CHECK", "BET_33", "BET_66"],
                'correct_action' => "BET_66",
                'explanation' => "BB puede liderar porque este board golpea muy fuerte su rango y Hero tiene combo draw enorme.",
                'solver_note' => "GTO simplificado: donk existe cuando el caller tiene clara ventaja de nuts.",
                'grades' => [
                    'CHECK' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                    'BET_33' => ['grade' => 'good', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                    'BET_66' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                ],
                'gto_insight' => "GTO simplificado: donk existe cuando el caller tiene clara ventaja de nuts.",
                'low_stakes_insight' => "En micros lidera con equity real; no donkees manos basura por ansiedad.",
                'confidence' => 84,
            ],
            [
                'id' => "pf_donk_842r_bb_vs_btn_88",
                'concept' => "set_dry",
                'concept_label' => "Donk con set en board seco",
                'title' => "BB vs BTN · 88 en 842r",
                'hero_position' => "BB",
                'villain_position' => "BTN",
                'hero_cards' => ["8h", "8d"],
                'board_cards' => ["8s", "4d", "2c"],
                'pot_bb' => 5.5,
                'spr' => 8.7,
                'effective_stack_bb' => 47.0,
                'board_texture' => "Board bajo seco",
                'range_advantage' => "BTN tiene overpairs; BB tiene sets bajos.",
                'nut_advantage' => "BB tiene más sets de 44/22 y algunos 8x.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: 8♠ 4♦ 2♣", "Action on Hero BB"],
                'options' => ["CHECK", "BET_33", "BET_66"],
                'correct_action' => "CHECK",
                'explanation' => "Aunque tienes set, el agresor preflop va a c-betear mucho. Check-raise suele capturar más EV que donk automático.",
                'solver_note' => "GTO simplificado: muchos sets del caller siguen entrando en check para proteger rango.",
                'grades' => [
                    'CHECK' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'BET_33' => ['grade' => 'marginal', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                    'BET_66' => ['grade' => 'marginal', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                ],
                'gto_insight' => "GTO simplificado: muchos sets del caller siguen entrando en check para proteger rango.",
                'low_stakes_insight' => "En NL2-NL10 deja que el agresor apueste; no mates su c-bet con donk innecesario.",
                'confidence' => 82,
            ],
            [
                'id' => "pf_donk_943ss_bb_vs_co_a5s",
                'concept' => "nfd_low_board",
                'concept_label' => "Donk con nut draw",
                'title' => "BB vs CO · A5s en 943ss",
                'hero_position' => "BB",
                'villain_position' => "CO",
                'hero_cards' => ["As", "5s"],
                'board_cards' => ["9s", "4s", "3d"],
                'pot_bb' => 5.5,
                'spr' => 8.4,
                'effective_stack_bb' => 48.0,
                'board_texture' => "Board bajo con color",
                'range_advantage' => "CO tiene overpairs; BB tiene pares/draws bajos.",
                'nut_advantage' => "BB tiene sets bajos y muchos draws.",
                'actions' => ["CO opens 2.5 BB", "BB calls", "Flop: 9♠ 4♠ 3♦", "Action on Hero BB"],
                'options' => ["CHECK", "BET_33", "BET_66"],
                'correct_action' => "BET_33",
                'explanation' => "Nut flush draw puede donkear pequeño en textura que conecta con BB y niega equity.",
                'solver_note' => "GTO simplificado: donk pequeño con draws fuertes protege y realiza equity.",
                'grades' => [
                    'CHECK' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                    'BET_33' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'BET_66' => ['grade' => 'good', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                ],
                'gto_insight' => "GTO simplificado: donk pequeño con draws fuertes protege y realiza equity.",
                'low_stakes_insight' => "En micros donkea proyectos fuertes solo en boards donde tu rango realmente conecta.",
                'confidence' => 80,
            ],
            [
                'id' => "pf_donk_ak7r_bb_vs_btn_kq",
                'concept' => "bad_donk_range_disadvantage",
                'concept_label' => "Donk malo en A-high",
                'title' => "BB vs BTN · KQ en AK7r",
                'hero_position' => "BB",
                'villain_position' => "BTN",
                'hero_cards' => ["Kh", "Qh"],
                'board_cards' => ["As", "Kd", "7c"],
                'pot_bb' => 5.5,
                'spr' => 8.6,
                'effective_stack_bb' => 47.0,
                'board_texture' => "A-K high seco",
                'range_advantage' => "BTN tiene enorme ventaja de rango.",
                'nut_advantage' => "BTN tiene AA/KK/AK/AQ; BB está dominado muchas veces.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: A♠ K♦ 7♣", "Action on Hero BB"],
                'options' => ["CHECK", "BET_33", "BET_66"],
                'correct_action' => "CHECK",
                'explanation' => "Donk aquí ataca contra un rango que domina este board. Mejor check-call o check-evaluar.",
                'solver_note' => "GTO simplificado: no lideres boards donde el agresor conserva ventaja fuerte.",
                'grades' => [
                    'CHECK' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'BET_33' => ['grade' => 'marginal', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                    'BET_66' => ['grade' => 'marginal', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                ],
                'gto_insight' => "GTO simplificado: no lideres boards donde el agresor conserva ventaja fuerte.",
                'low_stakes_insight' => "En NL2-NL10 no apuestes para “saber dónde estás”; eso pierde dinero.",
                'confidence' => 86,
            ],
            [
                'id' => "pf_donk_t98r_bb_vs_btn_j7s",
                'concept' => "straight_draw",
                'concept_label' => "Donk con OESD",
                'title' => "BB vs BTN · J7s en T98r",
                'hero_position' => "BB",
                'villain_position' => "BTN",
                'hero_cards' => ["Jh", "7h"],
                'board_cards' => ["Ts", "9d", "8c"],
                'pot_bb' => 5.5,
                'spr' => 8.0,
                'effective_stack_bb' => 47.0,
                'board_texture' => "Board conectado",
                'range_advantage' => "BB conecta muy bien con T98.",
                'nut_advantage' => "BB tiene más escaleras y dobles; BTN conserva overpairs.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: T♠ 9♦ 8♣", "Action on Hero BB"],
                'options' => ["CHECK", "BET_33", "BET_66"],
                'correct_action' => "BET_66",
                'explanation' => "Escalera abierta en board de ventaja BB puede liderar grande como semi-bluff.",
                'solver_note' => "GTO simplificado: donk grande aparece en boards dinámicos con ventaja de nuts.",
                'grades' => [
                    'CHECK' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                    'BET_33' => ['grade' => 'good', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                    'BET_66' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                ],
                'gto_insight' => "GTO simplificado: donk grande aparece en boards dinámicos con ventaja de nuts.",
                'low_stakes_insight' => "En micros, si donkeas, hazlo con equity clara y plan para turns.",
                'confidence' => 82,
            ],
            [
                'id' => "pf_donk_q72r_bb_vs_btn_77",
                'concept' => "middle_set",
                'concept_label' => "Set medio contra BTN",
                'title' => "BB vs BTN · 77 en Q72r",
                'hero_position' => "BB",
                'villain_position' => "BTN",
                'hero_cards' => ["7h", "7d"],
                'board_cards' => ["Qs", "7c", "2d"],
                'pot_bb' => 5.5,
                'spr' => 8.7,
                'effective_stack_bb' => 47.0,
                'board_texture' => "Q-high seco",
                'range_advantage' => "BTN tiene ventaja de rango.",
                'nut_advantage' => "BB tiene sets, BTN tiene mejores Qx y overpairs parciales.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: Q♠ 7♣ 2♦", "Action on Hero BB"],
                'options' => ["CHECK", "BET_33", "BET_66"],
                'correct_action' => "CHECK",
                'explanation' => "Con set medio en board seco, check deja que BTN c-betee sus Qx y faroles.",
                'solver_note' => "GTO simplificado: check protege rango y permite check-raise por valor.",
                'grades' => [
                    'CHECK' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'BET_33' => ['grade' => 'marginal', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                    'BET_66' => ['grade' => 'marginal', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                ],
                'gto_insight' => "GTO simplificado: check protege rango y permite check-raise por valor.",
                'low_stakes_insight' => "En microlímites no siempre donkees tus monstruos; deja que el agresor se equivoque.",
                'confidence' => 84,
            ],
            [
                'id' => "pf_donk_622ss_bb_vs_sb_a4s",
                'concept' => "blind_vs_blind_nfd",
                'concept_label' => "Donk en guerra de ciegas",
                'title' => "BB vs SB · A4s en 622ss",
                'hero_position' => "BB",
                'villain_position' => "SB",
                'hero_cards' => ["As", "4s"],
                'board_cards' => ["6s", "2d", "2s"],
                'pot_bb' => 4.5,
                'spr' => 9.4,
                'effective_stack_bb' => 42.0,
                'board_texture' => "Board emparejado bajo con FD",
                'range_advantage' => "SB tiene ventaja ligera; BB tiene muchos 2x/6x.",
                'nut_advantage' => "BB tiene más 2x defendidos y nut draws.",
                'actions' => ["SB completes", "BB checks", "Flop: 6♠ 2♦ 2♠", "Action on Hero BB"],
                'options' => ["CHECK", "BET_33", "BET_66"],
                'correct_action' => "BET_33",
                'explanation' => "En limp pot BvB, BB puede liderar pequeño con nut draw y fold equity.",
                'solver_note' => "GTO simplificado: en botes limpeados las donks pequeñas son más naturales.",
                'grades' => [
                    'CHECK' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                    'BET_33' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'BET_66' => ['grade' => 'good', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                ],
                'gto_insight' => "GTO simplificado: en botes limpeados las donks pequeñas son más naturales.",
                'low_stakes_insight' => "En micros apuesta pequeño con equity y cobra folds inmediatos.",
                'confidence' => 78,
            ],
            [
                'id' => "pf_donk_j85ss_bb_vs_co_jt",
                'concept' => "top_pair_dynamic",
                'concept_label' => "Donk top pair en dinámico",
                'title' => "BB vs CO · JT en J85ss",
                'hero_position' => "BB",
                'villain_position' => "CO",
                'hero_cards' => ["Jh", "Th"],
                'board_cards' => ["Js", "8s", "5d"],
                'pot_bb' => 5.5,
                'spr' => 8.3,
                'effective_stack_bb' => 48.0,
                'board_texture' => "J-high dinámico",
                'range_advantage' => "CO tiene overpairs; BB conecta pares y draws.",
                'nut_advantage' => "BB tiene dobles/sets; CO tiene overpairs fuertes.",
                'actions' => ["CO opens 2.5 BB", "BB calls", "Flop: J♠ 8♠ 5♦", "Action on Hero BB"],
                'options' => ["CHECK", "BET_33", "BET_66"],
                'correct_action' => "CHECK",
                'explanation' => "Top pair medio no quiere inflar bote OOP sin kicker premium. Check-call suele ser mejor.",
                'solver_note' => "GTO simplificado: no conviertas manos medias en apuestas vulnerables sin necesidad.",
                'grades' => [
                    'CHECK' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'BET_33' => ['grade' => 'marginal', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                    'BET_66' => ['grade' => 'marginal', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                ],
                'gto_insight' => "GTO simplificado: no conviertas manos medias en apuestas vulnerables sin necesidad.",
                'low_stakes_insight' => "En NL2-NL10 check-call y deja que faroleen/valoreen peor.",
                'confidence' => 80,
            ],
            [
                'id' => "pf_donk_432r_bb_vs_btn_65s",
                'concept' => "made_straight",
                'concept_label' => "Donk con escalera hecha",
                'title' => "BB vs BTN · 65s en 432r",
                'hero_position' => "BB",
                'villain_position' => "BTN",
                'hero_cards' => ["6h", "5h"],
                'board_cards' => ["4s", "3d", "2c"],
                'pot_bb' => 5.5,
                'spr' => 8.2,
                'effective_stack_bb' => 47.0,
                'board_texture' => "Board bajo conectado",
                'range_advantage' => "BB impacta muy fuerte.",
                'nut_advantage' => "BB tiene más escaleras y dobles bajas.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: 4♠ 3♦ 2♣", "Action on Hero BB"],
                'options' => ["CHECK", "BET_33", "BET_66"],
                'correct_action' => "BET_66",
                'explanation' => "Con escalera y ventaja clara de nuts, liderar grande es razonable para construir bote y negar equity.",
                'solver_note' => "GTO simplificado: donk aparece con mucha fuerza cuando el caller domina la textura.",
                'grades' => [
                    'CHECK' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                    'BET_33' => ['grade' => 'good', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                    'BET_66' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                ],
                'gto_insight' => "GTO simplificado: donk aparece con mucha fuerza cuando el caller domina la textura.",
                'low_stakes_insight' => "En micros apuesta por valor: overpairs y A5 no foldean fácil.",
                'confidence' => 86,
            ],
            [
                'id' => "pf_donk_k72r_bb_vs_btn_76s",
                'concept' => "bad_donk_air",
                'concept_label' => "Donk sin equity suficiente",
                'title' => "BB vs BTN · 76s en K72r",
                'hero_position' => "BB",
                'villain_position' => "BTN",
                'hero_cards' => ["7h", "6h"],
                'board_cards' => ["Ks", "7d", "2c"],
                'pot_bb' => 5.5,
                'spr' => 8.8,
                'effective_stack_bb' => 47.0,
                'board_texture' => "K-high seco",
                'range_advantage' => "BTN tiene gran ventaja de rango.",
                'nut_advantage' => "BTN tiene Kx fuertes; BB tiene pares medios.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: K♠ 7♦ 2♣", "Action on Hero BB"],
                'options' => ["CHECK", "BET_33", "BET_66"],
                'correct_action' => "CHECK",
                'explanation' => "Segundo par débil no debe donkear contra ventaja clara del agresor. Check-call o check-fold según sizing.",
                'solver_note' => "GTO simplificado: respeta la ventaja de rango del PFR en K-high seco.",
                'grades' => [
                    'CHECK' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'BET_33' => ['grade' => 'marginal', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                    'BET_66' => ['grade' => 'marginal', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                ],
                'gto_insight' => "GTO simplificado: respeta la ventaja de rango del PFR en K-high seco.",
                'low_stakes_insight' => "En microlímites no apuestes manos medias por miedo; juega simple.",
                'confidence' => 82,
            ],
        ];
    }
}
