<?php
namespace App\SpotTraining\Postflop\Modules;

use App\SpotTraining\Postflop\Concerns\BuildsPostflopSpots;

class FloatSpots
{
    use BuildsPostflopSpots;

    public static function all(): array
    {
        return array_map(fn (array $spot): array => self::build($spot), self::spots());
    }

    protected static function build(array $s): array
    {
        return self::spot(
            $s['id'],
            'float',
            'Float Flop',
            $s['concept'],
            $s['concept_label'],
            $s['title'],
            $s['hero_position'],
            $s['villain_position'],
            $s['hero_cards'],
            $s['board_cards'],
            $s['pot_bb'],
            $s['spr'],
            $s['effective_stack_bb'],
            $s['board_texture'],
            $s['range_advantage'],
            $s['nut_advantage'],
            $s['actions'],
            $s['options'],
            $s['correct_action'],
            $s['explanation'],
            $s['solver_note'],
            $s['grades'],
            $s['gto_insight'],
            $s['low_stakes_insight'],
            $s['confidence']
        );
    }

    protected static function spots(): array
    {
        return [
            [
                'id' => "pf_float_a72r_bb_vs_btn_kq",
                'concept' => "backdoor_air_fold",
                'concept_label' => "Float con overcards y backdoor",
                'title' => "BB vs BTN · KQ en A72r",
                'hero_position' => "BB",
                'villain_position' => "BTN",
                'hero_cards' => ["Kh", "Qh"],
                'board_cards' => ["As", "7d", "2c"],
                'pot_bb' => 8.0,
                'spr' => 7.1,
                'effective_stack_bb' => 47.0,
                'board_texture' => "A-high seco",
                'range_advantage' => "BTN tiene fuerte ventaja.",
                'nut_advantage' => "BTN domina Ax; BB tiene sets bajos ocasionales.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: A♠ 7♦ 2♣", "BB checks", "BTN bets 2.5 BB", "Action on Hero BB"],
                'options' => ["FOLD", "CALL", "RAISE"],
                'correct_action' => "FOLD",
                'explanation' => "KQ sin backdoor fuerte ni blocker suficiente no debe flotar demasiado contra A-high.",
                'solver_note' => "GTO simplificado: defiende algo, pero KQ sin equity clara suele foldear.",
                'grades' => [
                    'FOLD' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'CALL' => ['grade' => 'marginal', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                    'RAISE' => ['grade' => 'marginal', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                ],
                'gto_insight' => "GTO simplificado: defiende algo, pero KQ sin equity clara suele foldear.",
                'low_stakes_insight' => "En micros foldea aire bonito; no pagues solo porque tienes dos cartas altas.",
                'confidence' => 80,
            ],
            [
                'id' => "pf_float_q83r_bb_vs_btn_aj",
                'concept' => "overcards_backdoor_float",
                'concept_label' => "Float con overcards + backdoor",
                'title' => "BB vs BTN · AJ en Q83r",
                'hero_position' => "BB",
                'villain_position' => "BTN",
                'hero_cards' => ["Ah", "Jh"],
                'board_cards' => ["Qs", "8d", "3h"],
                'pot_bb' => 8.0,
                'spr' => 7.3,
                'effective_stack_bb' => 47.0,
                'board_texture' => "Q-high seco",
                'range_advantage' => "BTN tiene ventaja moderada.",
                'nut_advantage' => "BTN tiene mejores Qx; BB tiene sets bajos.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: Q♠ 8♦ 3♥", "BB checks", "BTN bets 2.5 BB", "Action on Hero BB"],
                'options' => ["FOLD", "CALL", "RAISE"],
                'correct_action' => "CALL",
                'explanation' => "AJ con backdoor color y escalera puede flotar una vez contra sizing pequeño.",
                'solver_note' => "GTO simplificado: overcards con backdoors continúan parte del tiempo.",
                'grades' => [
                    'FOLD' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                    'CALL' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'RAISE' => ['grade' => 'good', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                ],
                'gto_insight' => "GTO simplificado: overcards con backdoors continúan parte del tiempo.",
                'low_stakes_insight' => "En micros hazlo solo vs apuestas pequeñas y con plan: atacar turns favorables.",
                'confidence' => 78,
            ],
            [
                'id' => "pf_float_k94ss_bb_vs_btn_asj",
                'concept' => "nut_flush_draw_aggression",
                'concept_label' => "Float con nut flush draw",
                'title' => "BB vs BTN · AJs en K94ss",
                'hero_position' => "BB",
                'villain_position' => "BTN",
                'hero_cards' => ["As", "Js"],
                'board_cards' => ["Ks", "9d", "4s"],
                'pot_bb' => 8.0,
                'spr' => 7.0,
                'effective_stack_bb' => 47.0,
                'board_texture' => "K-high con FD",
                'range_advantage' => "BTN tiene ventaja, BB tiene draws.",
                'nut_advantage' => "Ambos tienen draws; BTN tiene Kx fuertes.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: K♠ 9♦ 4♠", "BB checks", "BTN bets 3 BB", "Action on Hero BB"],
                'options' => ["FOLD", "CALL", "RAISE"],
                'correct_action' => "CALL",
                'explanation' => "Nut flush draw puede pagar y también mezclar raise. Call conserva rangos peores y realiza equity.",
                'solver_note' => "GTO simplificado: NFD nunca es fold ante tamaño normal.",
                'grades' => [
                    'FOLD' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                    'CALL' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'RAISE' => ['grade' => 'good', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                ],
                'gto_insight' => "GTO simplificado: NFD nunca es fold ante tamaño normal.",
                'low_stakes_insight' => "En NL2-NL10 paga o sube draws fuertes; foldear aquí es error grave.",
                'confidence' => 86,
            ],
            [
                'id' => "pf_float_j76r_bb_vs_co_t9",
                'concept' => "clean_gutshot_continue",
                'concept_label' => "Float con OESD",
                'title' => "BB vs CO · T9 en J76r",
                'hero_position' => "BB",
                'villain_position' => "CO",
                'hero_cards' => ["Th", "9h"],
                'board_cards' => ["Js", "7d", "6c"],
                'pot_bb' => 8.0,
                'spr' => 6.8,
                'effective_stack_bb' => 48.0,
                'board_texture' => "Board conectado",
                'range_advantage' => "CO conserva overpairs; BB conecta mucho.",
                'nut_advantage' => "BB tiene dobles, sets y draws fuertes.",
                'actions' => ["CO opens 2.5 BB", "BB calls", "Flop: J♠ 7♦ 6♣", "BB checks", "CO bets 3 BB", "Action on Hero BB"],
                'options' => ["FOLD", "CALL", "RAISE"],
                'correct_action' => "CALL",
                'explanation' => "OESD con backdoor color debe continuar. Raise también existe, pero call es sólido.",
                'solver_note' => "GTO simplificado: proyectos abiertos defienden muy bien.",
                'grades' => [
                    'FOLD' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                    'CALL' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'RAISE' => ['grade' => 'good', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                ],
                'gto_insight' => "GTO simplificado: proyectos abiertos defienden muy bien.",
                'low_stakes_insight' => "En micros no tires proyectos fuertes por miedo; calcula equity.",
                'confidence' => 84,
            ],
            [
                'id' => "pf_float_t72r_bb_vs_btn_a5",
                'concept' => "overcards_backdoor_float",
                'concept_label' => "Float con A-high backdoor",
                'title' => "BB vs BTN · A5s en T72r",
                'hero_position' => "BB",
                'villain_position' => "BTN",
                'hero_cards' => ["Ah", "5h"],
                'board_cards' => ["Ts", "7d", "2h"],
                'pot_bb' => 8.0,
                'spr' => 7.2,
                'effective_stack_bb' => 47.0,
                'board_texture' => "T-high seco",
                'range_advantage' => "BTN tiene ventaja moderada.",
                'nut_advantage' => "BTN tiene overpairs; BB tiene sets bajos.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: T♠ 7♦ 2♥", "BB checks", "BTN bets 2 BB", "Action on Hero BB"],
                'options' => ["FOLD", "CALL", "RAISE"],
                'correct_action' => "CALL",
                'explanation' => "A5s con backdoor color, backdoor escalera y A-high puede flotar contra sizing pequeño.",
                'solver_note' => "GTO simplificado: vs c-bet pequeña se defiende más ancho con backdoors.",
                'grades' => [
                    'FOLD' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                    'CALL' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'RAISE' => ['grade' => 'good', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                ],
                'gto_insight' => "GTO simplificado: vs c-bet pequeña se defiende más ancho con backdoors.",
                'low_stakes_insight' => "En microlímites paga una vez si el tamaño es pequeño; no te cases si el turn no mejora.",
                'confidence' => 78,
            ],
            [
                'id' => "pf_float_983ss_bb_vs_btn_kq",
                'concept' => "fold_no_equity",
                'concept_label' => "Float malo sin equity",
                'title' => "BB vs BTN · KQ en 983ss",
                'hero_position' => "BB",
                'villain_position' => "BTN",
                'hero_cards' => ["Kh", "Qc"],
                'board_cards' => ["9s", "8s", "3d"],
                'pot_bb' => 8.0,
                'spr' => 6.9,
                'effective_stack_bb' => 47.0,
                'board_texture' => "Board medio dinámico",
                'range_advantage' => "BB conecta más; BTN tiene overcards/overpairs.",
                'nut_advantage' => "BB tiene más dobles/draws.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: 9♠ 8♠ 3♦", "BB checks", "BTN bets 5 BB", "Action on Hero BB"],
                'options' => ["FOLD", "CALL", "RAISE"],
                'correct_action' => "FOLD",
                'explanation' => "KQ sin pica y ante sizing grande tiene mala realización. Float aquí es perder dinero.",
                'solver_note' => "GTO simplificado: reduce floats sin equity frente a sizes grandes en boards dinámicos.",
                'grades' => [
                    'FOLD' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'CALL' => ['grade' => 'marginal', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                    'RAISE' => ['grade' => 'marginal', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                ],
                'gto_insight' => "GTO simplificado: reduce floats sin equity frente a sizes grandes en boards dinámicos.",
                'low_stakes_insight' => "En NL2-NL10 no pagues grande con aire; espera spots mejores.",
                'confidence' => 86,
            ],
            [
                'id' => "pf_float_qt4r_bb_vs_btn_kj",
                'concept' => "clean_gutshot_continue",
                'concept_label' => "Float con gutshot + overcard",
                'title' => "BB vs BTN · KJ en QT4r",
                'hero_position' => "BB",
                'villain_position' => "BTN",
                'hero_cards' => ["Kh", "Jh"],
                'board_cards' => ["Qs", "Td", "4c"],
                'pot_bb' => 8.0,
                'spr' => 7.0,
                'effective_stack_bb' => 47.0,
                'board_texture' => "Broadway conectado",
                'range_advantage' => "BTN tiene ventaja de rango.",
                'nut_advantage' => "Ambos tienen nuts; BTN más AQ/KJ, BB más dobles bajas.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: Q♠ T♦ 4♣", "BB checks", "BTN bets 2.5 BB", "Action on Hero BB"],
                'options' => ["FOLD", "CALL", "RAISE"],
                'correct_action' => "CALL",
                'explanation' => "KJ tiene gutshot a la escalera máxima y overcard. Call es estándar contra tamaño razonable.",
                'solver_note' => "GTO simplificado: gutshots con overcards buenas continúan.",
                'grades' => [
                    'FOLD' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                    'CALL' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'RAISE' => ['grade' => 'good', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                ],
                'gto_insight' => "GTO simplificado: gutshots con overcards buenas continúan.",
                'low_stakes_insight' => "En micros paga con equity real; si cae A/9/K/J puedes tomar mejores decisiones.",
                'confidence' => 80,
            ],
            [
                'id' => "pf_float_ak5r_bb_vs_btn_qj",
                'concept' => "backdoor_air_fold",
                'concept_label' => "Float dominado en A-K",
                'title' => "BB vs BTN · QJ en AK5r",
                'hero_position' => "BB",
                'villain_position' => "BTN",
                'hero_cards' => ["Qh", "Jh"],
                'board_cards' => ["As", "Kd", "5c"],
                'pot_bb' => 8.0,
                'spr' => 6.8,
                'effective_stack_bb' => 47.0,
                'board_texture' => "A-K high seco",
                'range_advantage' => "BTN aplasta este board.",
                'nut_advantage' => "BTN tiene sets, dobles y top pairs fuertes.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: A♠ K♦ 5♣", "BB checks", "BTN bets 2.5 BB", "Action on Hero BB"],
                'options' => ["FOLD", "CALL", "RAISE"],
                'correct_action' => "FOLD",
                'explanation' => "QJ tiene gutshot, pero está muy dominado y sufre reverse implied odds.",
                'solver_note' => "GTO simplificado: algunos gutshots se foldean cuando el rango rival domina demasiado.",
                'grades' => [
                    'FOLD' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'CALL' => ['grade' => 'marginal', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                    'RAISE' => ['grade' => 'marginal', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                ],
                'gto_insight' => "GTO simplificado: algunos gutshots se foldean cuando el rango rival domina demasiado.",
                'low_stakes_insight' => "En microlímites evita pagar por “a ver si cae el T” contra rangos fuertes.",
                'confidence' => 84,
            ],
            [
                'id' => "pf_float_654ss_bb_vs_btn_a3s",
                'concept' => "combo_draw_aggression",
                'concept_label' => "Float agresivo con draw fuerte",
                'title' => "BB vs BTN · A3s en 654ss",
                'hero_position' => "BB",
                'villain_position' => "BTN",
                'hero_cards' => ["As", "3s"],
                'board_cards' => ["6s", "5d", "4s"],
                'pot_bb' => 8.0,
                'spr' => 6.3,
                'effective_stack_bb' => 47.0,
                'board_texture' => "Board muy conectado con FD",
                'range_advantage' => "BB tiene gran ventaja de textura.",
                'nut_advantage' => "BB tiene escaleras, dobles y combo draws.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: 6♠ 5♦ 4♠", "BB checks", "BTN bets 3 BB", "Action on Hero BB"],
                'options' => ["FOLD", "CALL", "RAISE"],
                'correct_action' => "RAISE",
                'explanation' => "A3s tiene proyecto de color y escalera. Raise maximiza fold equity y construye cuando completas.",
                'solver_note' => "GTO simplificado: combo draws son candidatos excelentes para agresión.",
                'grades' => [
                    'FOLD' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                    'CALL' => ['grade' => 'good', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                    'RAISE' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                ],
                'gto_insight' => "GTO simplificado: combo draws son candidatos excelentes para agresión.",
                'low_stakes_insight' => "En NL2-NL10 esta es agresión buena: equity + fold equity, no bluff vacío.",
                'confidence' => 88,
            ],
            [
                'id' => "pf_float_j42r_bb_vs_btn_55",
                'concept' => "underpair_showdown_value",
                'concept_label' => "Float con par bajo",
                'title' => "BB vs BTN · 55 en J42r",
                'hero_position' => "BB",
                'villain_position' => "BTN",
                'hero_cards' => ["5h", "5d"],
                'board_cards' => ["Js", "4d", "2c"],
                'pot_bb' => 8.0,
                'spr' => 7.4,
                'effective_stack_bb' => 47.0,
                'board_texture' => "J-high seco",
                'range_advantage' => "BTN tiene ventaja moderada.",
                'nut_advantage' => "BTN tiene mejores Jx; BB tiene sets bajos.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: J♠ 4♦ 2♣", "BB checks", "BTN bets 2 BB", "Action on Hero BB"],
                'options' => ["FOLD", "CALL", "RAISE"],
                'correct_action' => "CALL",
                'explanation' => "55 tiene showdown value y puede pagar contra c-bet pequeña, pero debe foldear ante presión futura mala.",
                'solver_note' => "GTO simplificado: pares bajos continúan contra tamaños pequeños parte del tiempo.",
                'grades' => [
                    'FOLD' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                    'CALL' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'RAISE' => ['grade' => 'good', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                ],
                'gto_insight' => "GTO simplificado: pares bajos continúan contra tamaños pequeños parte del tiempo.",
                'low_stakes_insight' => "En micros paga pequeño una vez; no conviertas este par en hero call de tres calles.",
                'confidence' => 78,
            ],
        ];
    }
}
