<?php
namespace App\SpotTraining\Postflop\Modules;

use App\SpotTraining\Postflop\Concerns\BuildsPostflopSpots;

class OverbetSpots
{
    use BuildsPostflopSpots;

    public static function all(): array
    {
        return array_map(fn (array $spot): array => self::build($spot), self::spots());
    }

    protected static function build(array $s): array
    {
        return self::spot(
            $s['id'],
            'overbet',
            'Overbet Flop',
            $s['concept'],
            $s['concept_label'],
            $s['title'],
            $s['hero_position'],
            $s['villain_position'],
            $s['hero_cards'],
            $s['board_cards'],
            $s['pot_bb'],
            $s['spr'],
            $s['effective_stack_bb'],
            $s['board_texture'],
            $s['range_advantage'],
            $s['nut_advantage'],
            $s['actions'],
            $s['options'],
            $s['correct_action'],
            $s['explanation'],
            $s['solver_note'],
            $s['grades'],
            $s['gto_insight'],
            $s['low_stakes_insight'],
            $s['confidence']
        );
    }

    protected static function spots(): array
    {
        return [
            [
                'id' => "pf_overbet_a72r_btn_vs_bb_ak",
                'concept' => "dry_ace_high",
                'concept_label' => "Overbet en A-high seco",
                'title' => "BTN vs BB · AK en A72r",
                'hero_position' => "BTN",
                'villain_position' => "BB",
                'hero_cards' => ["Ah", "Kh"],
                'board_cards' => ["As", "7d", "2c"],
                'pot_bb' => 5.5,
                'spr' => 8.4,
                'effective_stack_bb' => 47.5,
                'board_texture' => "A-high seco",
                'range_advantage' => "BTN tiene fuerte ventaja de rango.",
                'nut_advantage' => "BTN domina Ax fuertes; BB tiene pocos sets.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: A♠ 7♦ 2♣", "BB checks", "Action on Hero BTN"],
                'options' => ["CHECK", "BET_33", "BET_125"],
                'correct_action' => "BET_33",
                'explanation' => "Aunque tienes ventaja, este board no necesita overbet de flop. Apuesta pequeña imprime EV contra mucho rango débil.",
                'solver_note' => "GTO simplificado: ventaja de rango alta suele usar sizing pequeño frecuente en flop seco.",
                'grades' => [
                    'CHECK' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                    'BET_33' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'BET_125' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                ],
                'gto_insight' => "GTO simplificado: ventaja de rango alta suele usar sizing pequeño frecuente en flop seco.",
                'low_stakes_insight' => "En microlímites apuesta pequeño por valor; no espantes manos peores con overbet innecesaria.",
                'confidence' => 84,
            ],
            [
                'id' => "pf_overbet_964r_bb_vs_btn_98",
                'concept' => "nut_advantage_bb",
                'concept_label' => "Overbet por ventaja de nuts",
                'title' => "BB vs BTN · 98 en 964r",
                'hero_position' => "BB",
                'villain_position' => "BTN",
                'hero_cards' => ["9h", "8h"],
                'board_cards' => ["9s", "6d", "4c"],
                'pot_bb' => 5.5,
                'spr' => 8.2,
                'effective_stack_bb' => 47.0,
                'board_texture' => "Board bajo conectado",
                'range_advantage' => "BTN tiene rango amplio, pero BB conecta mejor.",
                'nut_advantage' => "BB tiene más dobles, sets bajos y escaleras potenciales.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: 9♠ 6♦ 4♣", "BB checks", "BTN checks back? No", "Action on Hero BB after BTN bets 1.8 BB"],
                'options' => ["FOLD", "CALL", "RAISE"],
                'correct_action' => "RAISE",
                'explanation' => "Top pair con buena conectividad puede entrar en raises polarizados cuando BB tiene ventaja de nuts.",
                'solver_note' => "GTO simplificado: en boards que favorecen al defensor, algunos raises grandes presionan overcards y floats.",
                'grades' => [
                    'FOLD' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                    'CALL' => ['grade' => 'good', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                    'RAISE' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                ],
                'gto_insight' => "GTO simplificado: en boards que favorecen al defensor, algunos raises grandes presionan overcards y floats.",
                'low_stakes_insight' => "En NL2-NL10 no conviertas cualquier top pair en locura; sube más con valor/draws, no por ego.",
                'confidence' => 78,
            ],
            [
                'id' => "pf_overbet_t98ss_btn_vs_bb_jq",
                'concept' => "dynamic_combo_draw",
                'concept_label' => "Overbet con combo draw",
                'title' => "BTN vs BB · QJ en T98ss",
                'hero_position' => "BTN",
                'villain_position' => "BB",
                'hero_cards' => ["Qh", "Jh"],
                'board_cards' => ["Ts", "9s", "8d"],
                'pot_bb' => 5.5,
                'spr' => 8.0,
                'effective_stack_bb' => 47.5,
                'board_texture' => "Board muy dinámico",
                'range_advantage' => "BB conecta bastante; BTN conserva overpairs y broadways fuertes.",
                'nut_advantage' => "Ambos tienen nuts, BB tiene muchas dobles/sets.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: T♠ 9♠ 8♦", "BB checks", "Action on Hero BTN"],
                'options' => ["CHECK", "BET_66", "BET_125"],
                'correct_action' => "BET_66",
                'explanation' => "Tienes escalera abierta y overcards. La overbet existe, pero estándar más sólido es bet grande controlada.",
                'solver_note' => "GTO simplificado: board dinámico permite sizings grandes, pero no todo draw necesita overbet.",
                'grades' => [
                    'CHECK' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                    'BET_66' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'BET_125' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                ],
                'gto_insight' => "GTO simplificado: board dinámico permite sizings grandes, pero no todo draw necesita overbet.",
                'low_stakes_insight' => "En micros apuesta grande con equity real; evita overbetear si no sabes qué harás ante raise.",
                'confidence' => 80,
            ],
            [
                'id' => "pf_overbet_k72r_co_vs_bb_kk",
                'concept' => "top_set_dry",
                'concept_label' => "Overbet con top set",
                'title' => "CO vs BB · KK en K72r",
                'hero_position' => "CO",
                'villain_position' => "BB",
                'hero_cards' => ["Kh", "Kd"],
                'board_cards' => ["Ks", "7d", "2c"],
                'pot_bb' => 5.5,
                'spr' => 8.6,
                'effective_stack_bb' => 48.0,
                'board_texture' => "K-high seco",
                'range_advantage' => "CO tiene ventaja de rango.",
                'nut_advantage' => "CO tiene top sets y overpairs fuertes.",
                'actions' => ["CO opens 2.5 BB", "BB calls", "Flop: K♠ 7♦ 2♣", "BB checks", "Action on Hero CO"],
                'options' => ["CHECK", "BET_33", "BET_125"],
                'correct_action' => "BET_33",
                'explanation' => "Top set bloquea demasiado el rango que paga. En flop seco conviene apostar pequeño o inducir.",
                'solver_note' => "GTO simplificado: manos muy fuertes pueden mezclar, pero el sizing pequeño mantiene manos peores dentro.",
                'grades' => [
                    'CHECK' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                    'BET_33' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'BET_125' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                ],
                'gto_insight' => "GTO simplificado: manos muy fuertes pueden mezclar, pero el sizing pequeño mantiene manos peores dentro.",
                'low_stakes_insight' => "En NL2-NL10 no hace falta slowplay eterno; apuesta pequeño y deja que Kx/pares paguen.",
                'confidence' => 82,
            ],
            [
                'id' => "pf_overbet_q55r_btn_vs_bb_a5",
                'concept' => "trips_polar",
                'concept_label' => "Overbet con trips",
                'title' => "BTN vs BB · A5 en Q55r",
                'hero_position' => "BTN",
                'villain_position' => "BB",
                'hero_cards' => ["Ah", "5h"],
                'board_cards' => ["Qs", "5d", "5c"],
                'pot_bb' => 5.5,
                'spr' => 8.7,
                'effective_stack_bb' => 47.5,
                'board_texture' => "Board emparejado seco",
                'range_advantage' => "BTN tiene ventaja de rango general.",
                'nut_advantage' => "Ambos tienen 5x; BB defiende más 5x bajos.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: Q♠ 5♦ 5♣", "BB checks", "Action on Hero BTN"],
                'options' => ["CHECK", "BET_33", "BET_125"],
                'correct_action' => "BET_33",
                'explanation' => "Tienes trips, pero overbet flop reduce demasiado el rango rival. Pequeño captura más calls.",
                'solver_note' => "GTO simplificado: boards emparejados suelen jugarse con sizing pequeño frecuente.",
                'grades' => [
                    'CHECK' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                    'BET_33' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'BET_125' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                ],
                'gto_insight' => "GTO simplificado: boards emparejados suelen jugarse con sizing pequeño frecuente.",
                'low_stakes_insight' => "En microlímites saca valor de Qx y pares; no los eches con tamaño absurdo.",
                'confidence' => 84,
            ],
            [
                'id' => "pf_overbet_872ss_bb_vs_btn_76s",
                'concept' => "pair_draw_defender",
                'concept_label' => "Raise grande con pair+draw",
                'title' => "BB vs BTN · 76s en 872ss",
                'hero_position' => "BB",
                'villain_position' => "BTN",
                'hero_cards' => ["7s", "6s"],
                'board_cards' => ["8s", "7d", "2s"],
                'pot_bb' => 8.5,
                'spr' => 6.8,
                'effective_stack_bb' => 49.0,
                'board_texture' => "Board medio dinámico",
                'range_advantage' => "BTN tiene overpairs, BB conecta más con pares/draws.",
                'nut_advantage' => "BB tiene dobles, sets y muchos draws.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: 8♠ 7♦ 2♠", "BB checks", "BTN bets 3 BB", "Action on Hero BB"],
                'options' => ["FOLD", "CALL", "RAISE"],
                'correct_action' => "RAISE",
                'explanation' => "Par + flush draw tiene mucha equity y fold equity. Buen candidato para raise grande.",
                'solver_note' => "GTO simplificado: combos con equity robusta son buenos semi-bluffs agresivos.",
                'grades' => [
                    'FOLD' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                    'CALL' => ['grade' => 'good', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                    'RAISE' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                ],
                'gto_insight' => "GTO simplificado: combos con equity robusta son buenos semi-bluffs agresivos.",
                'low_stakes_insight' => "En NL2-NL10 este raise funciona mejor que farolear aire: si pagan, todavía tienes outs.",
                'confidence' => 82,
            ],
            [
                'id' => "pf_overbet_ak3r_3bp_sb_vs_btn_qq",
                'concept' => "overpair_3bet_pot",
                'concept_label' => "Overpair en 3Bet pot A-high",
                'title' => "SB vs BTN · QQ en AK3r",
                'hero_position' => "SB",
                'villain_position' => "BTN",
                'hero_cards' => ["Qh", "Qs"],
                'board_cards' => ["As", "Kd", "3c"],
                'pot_bb' => 18.0,
                'spr' => 4.2,
                'effective_stack_bb' => 76.0,
                'board_texture' => "A-K high en 3Bet pot",
                'range_advantage' => "SB tiene ventaja de rango fuerte.",
                'nut_advantage' => "SB tiene AA/KK/AK; BTN también tiene parte fuerte.",
                'actions' => ["BTN opens 2.5 BB", "SB 3-bets 10 BB", "BTN calls", "Flop: A♠ K♦ 3♣", "Action on Hero SB"],
                'options' => ["CHECK", "BET_33", "BET_125"],
                'correct_action' => "CHECK",
                'explanation' => "QQ tiene showdown value débil en este board. Overbet es quemar dinero: bloqueas manos que foldean y te pagan mejores.",
                'solver_note' => "GTO simplificado: no conviertas manos medias en faroles malos sin blockers adecuados.",
                'grades' => [
                    'CHECK' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'BET_33' => ['grade' => 'marginal', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                    'BET_125' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                ],
                'gto_insight' => "GTO simplificado: no conviertas manos medias en faroles malos sin blockers adecuados.",
                'low_stakes_insight' => "En micros check y controla; cuando pagan 3Bet, muchos Ax/Kx no foldean.",
                'confidence' => 86,
            ],
            [
                'id' => "pf_overbet_742r_btn_vs_bb_aa",
                'concept' => "overpair_dry",
                'concept_label' => "Overpair en board bajo seco",
                'title' => "BTN vs BB · AA en 742r",
                'hero_position' => "BTN",
                'villain_position' => "BB",
                'hero_cards' => ["Ah", "Ad"],
                'board_cards' => ["7s", "4d", "2c"],
                'pot_bb' => 5.5,
                'spr' => 8.8,
                'effective_stack_bb' => 48.0,
                'board_texture' => "Board bajo seco",
                'range_advantage' => "BTN conserva overpairs fuertes.",
                'nut_advantage' => "BB tiene algunos sets/dobles, BTN tiene overpairs.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: 7♠ 4♦ 2♣", "BB checks", "Action on Hero BTN"],
                'options' => ["CHECK", "BET_66", "BET_125"],
                'correct_action' => "BET_66",
                'explanation' => "AA quiere valor y protección. Grande está bien, overbet puede ser demasiado contra rango débil.",
                'solver_note' => "GTO simplificado: overpairs fuertes apuestan mucho, pero no necesitan polarizar al máximo siempre.",
                'grades' => [
                    'CHECK' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                    'BET_66' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'BET_125' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                ],
                'gto_insight' => "GTO simplificado: overpairs fuertes apuestan mucho, pero no necesitan polarizar al máximo siempre.",
                'low_stakes_insight' => "En NL2-NL10 apuesta por valor claro; 60-75% cobra a pares y draws sin aislarte tanto.",
                'confidence' => 84,
            ],
            [
                'id' => "pf_overbet_j76ss_co_vs_bb_asqs",
                'concept' => "nfd_overcards_pressure",
                'concept_label' => "Overbet con NFD + overcards",
                'title' => "CO vs BB · AQs en J76ss",
                'hero_position' => "CO",
                'villain_position' => "BB",
                'hero_cards' => ["As", "Qs"],
                'board_cards' => ["Js", "7s", "6d"],
                'pot_bb' => 5.5,
                'spr' => 8.3,
                'effective_stack_bb' => 48.0,
                'board_texture' => "Board dinámico con color",
                'range_advantage' => "BB conecta bien, CO tiene overpairs y broadways.",
                'nut_advantage' => "BB tiene sets/dobles; CO tiene overpairs y nut draws.",
                'actions' => ["CO opens 2.5 BB", "BB calls", "Flop: J♠ 7♠ 6♦", "BB checks", "Action on Hero CO"],
                'options' => ["CHECK", "BET_66", "BET_125"],
                'correct_action' => "BET_66",
                'explanation' => "Nut flush draw + overcard puede apostar grande, pero overbet de flop no es obligatoria.",
                'solver_note' => "GTO simplificado: semi-bluffs fuertes usan tamaños grandes en boards dinámicos.",
                'grades' => [
                    'CHECK' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                    'BET_66' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'BET_125' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                ],
                'gto_insight' => "GTO simplificado: semi-bluffs fuertes usan tamaños grandes en boards dinámicos.",
                'low_stakes_insight' => "En micros apuesta fuerte con equity, pero evita líneas que no puedas continuar en turn.",
                'confidence' => 82,
            ],
            [
                'id' => "pf_overbet_qq3r_btn_vs_bb_air",
                'concept' => "bad_overbet_air",
                'concept_label' => "Overbet bluff malo",
                'title' => "BTN vs BB · A4 en QQ3r",
                'hero_position' => "BTN",
                'villain_position' => "BB",
                'hero_cards' => ["Ah", "4h"],
                'board_cards' => ["Qs", "Qd", "3c"],
                'pot_bb' => 5.5,
                'spr' => 8.9,
                'effective_stack_bb' => 47.5,
                'board_texture' => "Board emparejado seco",
                'range_advantage' => "BTN tiene ventaja de rango, pero ambos tienen Qx.",
                'nut_advantage' => "BTN tiene algunas Qx fuertes; BB defiende muchas Qx.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: Q♠ Q♦ 3♣", "BB checks", "Action on Hero BTN"],
                'options' => ["CHECK", "BET_33", "BET_125"],
                'correct_action' => "BET_33",
                'explanation' => "A4 tiene blocker al As pero poca equity. Si apuestas, pequeño. Overbet bluff aquí es innecesario.",
                'solver_note' => "GTO simplificado: boards emparejados secos se atacan pequeño, no con faroles gigantes.",
                'grades' => [
                    'CHECK' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                    'BET_33' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'BET_125' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                ],
                'gto_insight' => "GTO simplificado: boards emparejados secos se atacan pequeño, no con faroles gigantes.",
                'low_stakes_insight' => "En NL2-NL10 no intentes representar monstruos con aire: te pagarán Qx y pares por curiosidad.",
                'confidence' => 82,
            ],
            [
                'id' => "pf_overbet_543ss_bb_vs_btn_65s",
                'concept' => "made_plus_draw",
                'concept_label' => "Raise polar con par + draw",
                'title' => "BB vs BTN · 65s en 543ss",
                'hero_position' => "BB",
                'villain_position' => "BTN",
                'hero_cards' => ["6s", "5s"],
                'board_cards' => ["5h", "4s", "3s"],
                'pot_bb' => 8.5,
                'spr' => 6.2,
                'effective_stack_bb' => 49.0,
                'board_texture' => "Board muy conectado",
                'range_advantage' => "BB conecta muchísimo con este board.",
                'nut_advantage' => "BB tiene más escaleras, dobles y draws fuertes.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: 5♥ 4♠ 3♠", "BB checks", "BTN bets 3 BB", "Action on Hero BB"],
                'options' => ["FOLD", "CALL", "RAISE"],
                'correct_action' => "RAISE",
                'explanation' => "Par + escalera abierta + flush draw es una mano enorme para jugar agresivo.",
                'solver_note' => "GTO simplificado: ventaja de nuts del defensor permite raises grandes con valor y combo draws.",
                'grades' => [
                    'FOLD' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                    'CALL' => ['grade' => 'good', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                    'RAISE' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                ],
                'gto_insight' => "GTO simplificado: ventaja de nuts del defensor permite raises grandes con valor y combo draws.",
                'low_stakes_insight' => "En micros este raise imprime EV: muchos overpairs pagan y tú tienes muchísima equity.",
                'confidence' => 88,
            ],
            [
                'id' => "pf_overbet_a98r_btn_vs_bb_t7s",
                'concept' => "gutshot_bad_overbet",
                'concept_label' => "Gutshot sin suficiente equity",
                'title' => "BTN vs BB · T7s en A98r",
                'hero_position' => "BTN",
                'villain_position' => "BB",
                'hero_cards' => ["Th", "7h"],
                'board_cards' => ["As", "9d", "8c"],
                'pot_bb' => 5.5,
                'spr' => 8.5,
                'effective_stack_bb' => 47.5,
                'board_texture' => "A-high conectado medio",
                'range_advantage' => "BTN tiene ventaja de rango por Ax.",
                'nut_advantage' => "BB tiene dobles/sets y conectores.",
                'actions' => ["BTN opens 2.5 BB", "BB calls", "Flop: A♠ 9♦ 8♣", "BB checks", "Action on Hero BTN"],
                'options' => ["CHECK", "BET_33", "BET_125"],
                'correct_action' => "CHECK",
                'explanation' => "T7s tiene gutshot, pero poca fold equity y mala realización si te pagan. Check es más disciplinado.",
                'solver_note' => "GTO simplificado: no todos los backdoors/gutshots son apuestas; selecciona equity y blockers.",
                'grades' => [
                    'CHECK' => ['grade' => 'best', 'frequency' => 62, 'ev_score' => 86, 'feedback' => 'Mejor decisión para este spot.'],
                    'BET_33' => ['grade' => 'marginal', 'frequency' => 28, 'ev_score' => 72, 'feedback' => 'Jugable en baja frecuencia, pero no es la línea principal.'],
                    'BET_125' => ['grade' => 'mistake', 'frequency' => 10, 'ev_score' => 35, 'feedback' => 'Pierde EV contra este rango y textura.'],
                ],
                'gto_insight' => "GTO simplificado: no todos los backdoors/gutshots son apuestas; selecciona equity y blockers.",
                'low_stakes_insight' => "En NL2-NL10 este tipo de overbet bluff no funcionará lo suficiente.",
                'confidence' => 80,
            ],
        ];
    }
}
